package com.mediflow.audit.repository;

import com.mediflow.audit.entity.AuditLog;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;

public interface AuditLogRepository
        extends JpaRepository<AuditLog, Long> {

    // PURPOSE:
    // Find all audit logs generated by a particular user.
    //
    // WHY:
    // Useful when we want to see the activity history of a user/admin.
    List<AuditLog> findByUserEmail(String userEmail);

    // PURPOSE:
    // Find audit history for a particular entity.
    //
    // Example:
    // All actions performed on Order ID 21.
    List<AuditLog> findByEntityTypeAndEntityId(
            String entityType,
            Long entityId
    );
}