package com.mediflow.payment.dto;

import com.mediflow.payment.entity.PaymentStatus;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class PaymentWebhookRequestDto {

    // PURPOSE:
    // Identifies which payment the payment gateway is updating.
    //
    // WHY:
    // The webhook must know which payment record should be updated.
    @NotNull(message = "Payment ID is required")
    private Long paymentId;


    // PURPOSE:
    // Represents the result received from the payment gateway.
    //
    // EXPECTED VALUES:
    // SUCCESS or FAILED.
    //
    // WHY:
    // Our application uses this value to update the payment status.
    @NotNull(message = "Payment status is required")
    private PaymentStatus status;


    // PURPOSE:
    // Stores the transaction reference generated by the payment gateway.
    //
    // WHY:
    // A transaction ID allows us to track the payment with the
    // external payment provider.
    @NotBlank(message = "Transaction ID is required")
    private String transactionId;
}