package com.mediflow.medicine.exception;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

@RestControllerAdvice
// PURPOSE:
// Provides centralized exception handling for all controllers.
//
// WHY:
// Instead of writing try-catch blocks inside every controller,
// exceptions can be handled from one common class.
public class GlobalExceptionHandler {


    @ExceptionHandler(MedicineNotFoundException.class)
    // PURPOSE:
    // Handle medicine-not-found errors centrally.
    //
    // WHY:
    // If medicine does not exist, return HTTP 404.
    public ResponseEntity<ErrorResponse> handleMedicineNotFound(
            MedicineNotFoundException ex) {

        ErrorResponse errorResponse = new ErrorResponse(
                HttpStatus.NOT_FOUND.value(),
                ex.getMessage(),
                LocalDateTime.now(),
                null
        );

        return ResponseEntity
                .status(HttpStatus.NOT_FOUND)
                .body(errorResponse);
    }


    @ExceptionHandler(OrderNotFoundException.class)
    // PURPOSE:
    // Handle order-not-found errors centrally.
    //
    // WHY:
    // If order does not exist, return HTTP 404.
    public ResponseEntity<ErrorResponse> handleOrderNotFound(
            OrderNotFoundException ex) {

        ErrorResponse errorResponse = new ErrorResponse(
                HttpStatus.NOT_FOUND.value(),
                ex.getMessage(),
                LocalDateTime.now(),
                null
        );

        return ResponseEntity
                .status(HttpStatus.NOT_FOUND)
                .body(errorResponse);
    }


    @ExceptionHandler(PrescriptionNotFoundException.class)
    // PURPOSE:
    // Handle prescription-not-found errors centrally.
    //
    // WHY:
    // If prescription does not exist, return HTTP 404.
    public ResponseEntity<ErrorResponse> handlePrescriptionNotFound(
            PrescriptionNotFoundException ex) {

        ErrorResponse errorResponse = new ErrorResponse(
                HttpStatus.NOT_FOUND.value(),
                ex.getMessage(),
                LocalDateTime.now(),
                null
        );

        return ResponseEntity
                .status(HttpStatus.NOT_FOUND)
                .body(errorResponse);
    }


    @ExceptionHandler(PaymentNotFoundException.class)
    // PURPOSE:
    // Handle payment-not-found errors centrally.
    //
    // WHY:
    // If payment does not exist, return HTTP 404.
    public ResponseEntity<ErrorResponse> handlePaymentNotFound(
            PaymentNotFoundException ex) {

        ErrorResponse errorResponse = new ErrorResponse(
                HttpStatus.NOT_FOUND.value(),
                ex.getMessage(),
                LocalDateTime.now(),
                null
        );

        return ResponseEntity
                .status(HttpStatus.NOT_FOUND)
                .body(errorResponse);
    }


    @ExceptionHandler(MethodArgumentNotValidException.class)
    // PURPOSE:
    // Handle validation errors generated by @Valid.
    //
    // EXAMPLE:
    // @NotBlank
    // @NotNull
    // @Email
    // @Min
    //
    // WHY:
    // Client should receive all validation errors
    // in a clear and standard format.
    public ResponseEntity<ErrorResponse> handleValidationErrors(
            MethodArgumentNotValidException ex) {

        // PURPOSE:
        // Store field name and corresponding validation message.
        //
        // EXAMPLE:
        // email    -> "Email is required"
        // password -> "Password is required"
        Map<String, String> errors = new HashMap<>();


        // PURPOSE:
        // Extract all field-level validation errors.
        ex.getBindingResult()
                .getFieldErrors()
                .forEach(error ->
                        errors.put(
                                error.getField(),
                                error.getDefaultMessage()
                        )
                );


        // PURPOSE:
        // Create a standard validation error response.
        ErrorResponse errorResponse = new ErrorResponse(
                HttpStatus.BAD_REQUEST.value(),
                "Validation failed",
                LocalDateTime.now(),
                errors
        );


        // PURPOSE:
        // Return HTTP 400 with validation details.
        return ResponseEntity
                .status(HttpStatus.BAD_REQUEST)
                .body(errorResponse);
    }


    @ExceptionHandler(IllegalArgumentException.class)
    // PURPOSE:
    // Handle invalid business/request conditions.
    //
    // EXAMPLES:
    // Invalid order status
    // Invalid payment status
    // Duplicate webhook
    // Invalid webhook secret
    public ResponseEntity<ErrorResponse> handleIllegalArgumentException(
            IllegalArgumentException ex) {

        ErrorResponse errorResponse = new ErrorResponse(
                HttpStatus.BAD_REQUEST.value(),
                ex.getMessage(),
                LocalDateTime.now(),
                null
        );

        return ResponseEntity
                .status(HttpStatus.BAD_REQUEST)
                .body(errorResponse);
    }
}